# Lokal im Container ohne TLS, von außen NUR verschlüsselt und mit Passwort
local   all  all                 trust
host    all  all  127.0.0.1/32   scram-sha-256
hostssl all  all  0.0.0.0/0      scram-sha-256
hostssl all  all  ::/0           scram-sha-256
